// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRXgDM7jf5xkUSlNdVhCgioRvdKOyZ43A',
    appId: '1:338952297:web:cae96ef3e193e8221fe2f8',
    messagingSenderId: '338952297',
    projectId: 'projeto-pdm-cce72',
    authDomain: 'projeto-pdm-cce72.firebaseapp.com',
    storageBucket: 'projeto-pdm-cce72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADzEoV1NPiH0KubHItI5b7xbPWe-EAepU',
    appId: '1:338952297:android:6bef239260df4cd41fe2f8',
    messagingSenderId: '338952297',
    projectId: 'projeto-pdm-cce72',
    storageBucket: 'projeto-pdm-cce72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA31phMh208Lh2LBYEYrvqQ-nR8WMscDBw',
    appId: '1:338952297:ios:360ce0475a1d4ed51fe2f8',
    messagingSenderId: '338952297',
    projectId: 'projeto-pdm-cce72',
    storageBucket: 'projeto-pdm-cce72.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA31phMh208Lh2LBYEYrvqQ-nR8WMscDBw',
    appId: '1:338952297:ios:360ce0475a1d4ed51fe2f8',
    messagingSenderId: '338952297',
    projectId: 'projeto-pdm-cce72',
    storageBucket: 'projeto-pdm-cce72.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRXgDM7jf5xkUSlNdVhCgioRvdKOyZ43A',
    appId: '1:338952297:web:8967358f3679a3e61fe2f8',
    messagingSenderId: '338952297',
    projectId: 'projeto-pdm-cce72',
    authDomain: 'projeto-pdm-cce72.firebaseapp.com',
    storageBucket: 'projeto-pdm-cce72.appspot.com',
  );
}
